### ISSUE TITLE
Cannot Post to Story From Gallery

### ISSUE THREAD

**Issue by JHVH13** [Programming4life/SnapColors#10]
When I share a picture from the gallery, and try to upload it to my story, I get a "Failed to upload error"
Shared pictures can be sent to other users successfully, but they simply fail to post to the story no matter what.

What I know:
I am using the correct versions: Snapchat 9.13.1.0 Beta and Snapcolors 3.4.4
I am not pressing the Snapchat icon, I am pressing the SnapColors icon when sharing from gallery.
I can post pictures taken by Snapchat to my story no problem.
Pressing the "add to story" button does not work.
Selecting "story" after pressing the send button does not work.
Sending to story and multiple users only results in users receiving the snaps.
All failurs to post result in a red menu button next to my story that reads "1 snap failed to post" 

Also, I read the sticky on xda and it said to report issues/bugs on github. I'm new to github and I hope this is the correct place to post about this.

**Comment by manvir-singh** [comment]
May seem stupid but check to see if you can post a regular snap to the story. Post your xposed log on http://pastebin.com/

**Comment by JHVH13** [comment]
I checked and I can post regular snaps to my story, just not uploads (sorry i didn't mention that). I'm running the latest xposed, snapcolors, and snapchat beta. I disabled all other modules for possible conflicts, then rebooted, then tried to upload a screenshot to my story. This is my xposed log right after I got "failed to post" I don't think its very helpful. any other logger apps or anything? I'm on an official CM12 build with supersu.

http://pastebin.com/SmGak3nS

Matthew Stout

**Comment by Hundredthtree3** [comment]
Same issue as above I cant post from gallery to story and I did everything I could possibly do but it keeps showing a red exclamation point saying snap failed to post. The only way I can fix it is by downloading the older snapchat version and the older snapcolors version before the latest updates. Also when I click share and click on snapcolours on a picture it sometimes opens it in snapchat and when I send a picture to someone it sends it in the chat and not in a snap like it did before the latest update but this seems to only happen like 20% of the time or something.

**Comment by Hundredthtree3** [comment]
*******it opens it in snapchat and when I send thr opened picture to someone it sends

**Comment by manvir-singh** [comment]
Thanks for letting me know I'm looking into this right now.

**Comment by Hundredthtree3** [comment]
Ight real guy thanks
