### ISSUE TITLE
No stories of my friends.

### ISSUE THREAD

**Issue by MrSmokeFace** [Programming4life/SnapColors#11]
Everytime when I install snapcolours on my rooted Galaxy S5 and open snapchat my friends their stories are gone. Snap and snapcolours are on the latest version.

**Comment by manvir-singh** [comment]
I need SnapChats version number? Beta or not?

**Comment by manvir-singh** [comment]
This issues going to be closed if I don't get a version number.

**Comment by MrSmokeFace** [comment]
V9.13.1.0 Beta, sorry for late respond.

**Comment by manvir-singh** [comment]
Clear SnapColors data and then reboot.

**Comment by manvir-singh** [comment]
Guessing this is solved.
