### ISSUE TITLE
Full caption and coloured text not working 

### ISSUE THREAD

**Issue by Unanymosh** [Programming4life/SnapColors#12]
Does not seem to be working for the latest version of snapchat it seems to be mixed with the new snapchat emoji icon too

**Comment by manvir-singh** [comment]
SnapColors version number and SnapChat version number?

**Comment by Unanymosh** [comment]
Snapcolors 3.4.6 
Snapchat version v9.14.1.0

**Comment by manvir-singh** [comment]
Your using an old version of SnapColors latest version is 3.4.7. http://repo.xposed.info/module/com.manvir.snapcolors

**Comment by Unanymosh** [comment]
Thanks boss
