### ISSUE TITLE
Doesn't work latest Beta

### ISSUE THREAD

**Issue by t3chguy** [Programming4life/SnapColors#14]
Running SnapColors v3.4.12
Snapchat v9.17.1.0 Beta

Features don't work and clicking anything within rainbow T results in force close

**Comment by manvir-singh** [comment]
Working on an update.

**Comment by t3chguy** [comment]
Great to hear, looking forward to being able to see SnapColors for myself (only just found out about it)

**Comment by skippy42p** [comment]
I have a samsung galaxy s6 edge 5.1.1 lollipop rooted xposed installer installed directly to system i installed the snapcolors app through xposed and set the settings and it only forces snapchat to close. I have done everything with my rooting knowledge and experience and for the life of me i cant get the apk to work

**Comment by manvir-singh** [comment]
Deprecated
