### ISSUE TITLE
Multi line feature in Snapchat for android 5.1.1 produces ActionDone effect upon pressing enter.

### ISSUE THREAD

**Issue by AllanWang** [Programming4life/SnapColors#2]
As mentioned on xda, if I type something in the caption and press enter, the cursor will go down a line (making a new line), but will also close the keyboard. I referenced you to the following line:

android:imeOptions="actionDone|flagNoExtractUi"

But I believe that that is present in prelollipop versions as well, and should therefore be addressed already. I am by no means a developer, but I will be happy to assist with anything I can. I am using Snapchat v9.7.3.0, which is the latest stable version on the play store for me, with a Nexus 5 on android 5.1.1 (Euphoria rom specifically).

**Comment by manvir-singh** [comment]
Does this only happen on Euphoria rom?

**Comment by AllanWang** [comment]
I don't believe it is limited to just the euphoria rom, but I haven't tested it on any other one. I'll try cyanogenmod when I have time

**Comment by manvir-singh** [comment]
okay. No one else has reported this bug so i dont know whats going on. It could be an edge case.

**Comment by AllanWang** [comment]
Keep in mind that the newest xposed for Android 5.1.1 was just released two days ago. There are likely people who have not yet tried it.

**Comment by manvir-singh** [comment]
yup i know.

**Comment by manvir-singh** [comment]
Are you using SnapChat Beta?

**Comment by AllanWang** [comment]
Nope. As mentioned I am in the latest stable. I don't use beta because I understand it can break support

**Comment by manvir-singh** [comment]
Try this version of SnapColors: https://programming4life.com/t.apk

**Comment by AllanWang** [comment]
That's it! You fixed it :)
