### ISSUE TITLE
Opening image for gallery not working.

### ISSUE THREAD

**Issue by Stillerman** [Programming4life/SnapColors#3]
When I try to select a photo from the main camera page, when I click the little square, I get sent back to the page of snapchat threads.

**Comment by manvir-singh** [comment]
Looking into it. I think its because Snapchat released a update.

**Comment by manvir-singh** [comment]
What version of SnapChat are you using?

**Comment by Stillerman** [comment]
9.10.0.0 Beta

**Comment by manvir-singh** [comment]
Can you post a video or picture of it?
