### ISSUE TITLE
Certain images not opening from Gallery in Snapchat

### ISSUE THREAD

**Issue by k3nHD** [Programming4life/SnapColors#4]
Version of Snapchat: 9.10.0.0
Version of Snapcolor: 3.3.3
Phone: Samsung Galaxy S4 T-Mobile

I can open images from the gallery in Snapchat properly if the image was originally taken using the Snapchat camera. However, I cannot open images from the gallery in Snapchat when I select images I originally took on my phone camera. When it fails and defaults back to the Snapchat camera screen. I have already tried both the stable version and the "bleeding edge" version with the same results.

**Comment by manvir-singh** [comment]
Are you able to post a image that causes this?

**Comment by k3nHD** [comment]
Yes hold on. 

https://www.dropbox.com/s/vef508prxdhlnl0/IMG_20150620_021607.jpg?dl=0

**Comment by manvir-singh** [comment]
Post your xposed log. Do not copy and past post it as a attachment.

**Comment by k3nHD** [comment]
It wont let me upload the xposed log as GitHub only permit PNG, GIF and JPG files. I uploaded it on my dropbox instead. 

https://www.dropbox.com/s/v64gwvshukb615e/xposed_error_20150621_115850.log?dl=0

**Comment by manvir-singh** [comment]
I forgot. I need the full log so use adb logcat if you could to get the log.

**Comment by manvir-singh** [comment]
Try this version I think I may have fixed it. Do'nt test it once with one image test it multiple times with diffrent images. https://programming4life.com/github-test.apk

**Comment by k3nHD** [comment]
Sorry for the delayed response. I was trying to figure out how to use alogcat. I have tested exactly 25 pictures of different resolutions and they work! I also was successful after restarting my phone multiple times! Thank you so much!

**Comment by manvir-singh** [comment]
Your welcome. I'm going to leave this issue open until tomorrow just in case the bug returns.
