### ISSUE TITLE
Images while sharing from gallery are automatically cropped 

### ISSUE THREAD

**Issue by Shubham-Rajpal** [Programming4life/SnapColors#5]
Images are automatically rotated a d cropped plz enable an option of image rotation or crop something  like that it will help

**Comment by manvir-singh** [comment]
The cropping and rotation of images is all handled by SnapChat. If you go into a chat and select a image to send from the gallery it should behave the same way as if you shared directly from the share via menu in the gallery. I'll be adding a option in a future release to rotate and crop images manually.
