### ISSUE TITLE
Screenshot detection feature not working

### ISSUE THREAD

**Issue by Unanymosh** [Programming4life/SnapColors#6]
Hey there! 

i love this module but the only slight issue i have with it is that the disable screenshot detection feature does not work, or at least with my phone anyway. I have a Sony Xperia Z and whenever i turn the disable screenshot detection feature on and i screenshot a text chat on Snapchat it says that i have taken a screenshot of the chat.

**Comment by manvir-singh** [comment]
Do you have "Screenshot Detection" Checked in the settings?

**Comment by Unanymosh** [comment]
Nevermind lol its working now lol
