### ISSUE TITLE
add option to remove "xyz is typing..." notifications

### ISSUE THREAD

**Issue by Justasic** [Programming4life/SnapColors#7]
It annoys me when I get 2 notifications for one message and snapchat by default has no way of disabling this functionality (or if it does, its unintuitively hidden).

**Comment by manvir-singh** [comment]
I've never gotten two notifactions for one message. Maybe a bug in Snapchat or something else.

**Comment by Justasic** [comment]
It isn't a bug, its a "feature" where snapchat says "xyz is typing..." And then gives another notification saying "xyz sent a message!" Thus giving 2 notifications. I could give a shit if someone is typing a message, I care when someone has /sent/ me a message.

I apologize if I was unclear

**Comment by manvir-singh** [comment]
This is a small thing that I don't think many people are going to be using or care about therefor I'll add this in when I have nothing else to do.

**Comment by Justasic** [comment]
http://imgur.com/a/NUR1e

One says "is typing" and arrives before the persons name with just the chat icon and no other text. The bubble changes text but it gives two notification events to the android system making it irritating when your phone vibrates and you're greeted with someone making up their mind on what they want rumor they want to spread.

**Comment by Justasic** [comment]
Ah, thanks
