### ISSUE TITLE
Bug with stories + Force  close 

### ISSUE THREAD

**Issue by AlphasSignature** [Programming4life/SnapColors#8]
Unable to see any story. The story page only shows letters. Also experiencing force close. 
Thank you.

**Comment by manvir-singh** [comment]
The stories not showing up can be fixed by Clearing SnapColors data. As for the fc I don't think its related to SnapColors but post your xposed log. You should try disable SnapColors and see if it still crashes.

**Comment by manvir-singh** [comment]
Looks like the fc is SnapChat related others have it too.

**Comment by AlphasSignature** [comment]
I actually find out the solution for the bug with the stories. In the 'Stories' section in SnapColors in Block Stories there is a hidden blocked stories named "'" you can't see it but when you click on it, it will ask you if you want to remove it click yes and that's it stories are back  in Snapchat. 
Thank you for everything 😊 .
