### ISSUE TITLE
Disable screenshot detection is not working.

### ISSUE THREAD

**Issue by trefase** [Programming4life/SnapColors#9]
Not working in the latest snapchat update.

**Comment by manvir-singh** [comment]
Snapchat version number? Also beta or not? Also SnapColors version number?

**Comment by trefase** [comment]
Snapchat v9.11.0.0
SnapColors 3.3.10
No beta.

**Comment by manvir-singh** [comment]
I just tested this and it works. I'm releasing a update in a min or two. That may fix it for you.
